INSERT INTO PRODUTO (COD_PRODUTO, DES_PRODUTO, STA_STATUS)
VALUES ('0001', 'Produto Corrente', 'A');

INSERT INTO PRODUTO (COD_PRODUTO, DES_PRODUTO, STA_STATUS)
VALUES ('0002', 'Produto Investimento', 'A');

INSERT INTO PRODUTO (COD_PRODUTO, DES_PRODUTO, STA_STATUS)
VALUES ('0003', 'Produto Credito', 'A');

INSERT INTO PRODUTO_COSIF (COD_PRODUTO, COD_COSIF, COD_CLASSIFICACAO, STA_STATUS)
VALUES ('0001', '11000000001', '110001', 'A');

INSERT INTO PRODUTO_COSIF (COD_PRODUTO, COD_COSIF, COD_CLASSIFICACAO, STA_STATUS)
VALUES ('0001', '11000000002', '110002', 'A');

INSERT INTO PRODUTO_COSIF (COD_PRODUTO, COD_COSIF, COD_CLASSIFICACAO, STA_STATUS)
VALUES ('0002', '12000000001', '120001', 'A');

INSERT INTO PRODUTO_COSIF (COD_PRODUTO, COD_COSIF, COD_CLASSIFICACAO, STA_STATUS)
VALUES ('0003', '13000000001', '130001', 'A');

INSERT INTO MOVIMENTO_MANUAL (
    DAT_MES,
    DAT_ANO,
    NUM_LANCAMENTO,
    COD_PRODUTO,
    COD_COSIF,
    DES_DESCRICAO,
    DAT_MOVIMENTO,
    COD_USUARIO,
    VAL_VALOR
) VALUES (
             7,
             2026,
             1,
             '0001',
             '11000000001',
             'Movimento inicial de teste',
             CURRENT_TIMESTAMP,
             'TESTE',
             1000.00
         );